Repository Pre-loved-Project/frontend, pull requests merged in 2025-10, with the labels that each got.

#20 feat: 공통 api fetch 함수
  src/shared/api/fetcher.ts
Labels: Feature

#21 feat: 인증 상태 관리 store 구현
  package-lock.json
  package.json
  src/features/auth/model/auth.store.ts
Labels: Feature

#28 회원가입 페이지 추가
  package-lock.json
  package.json
  src/app/signup/page.tsx
  src/features/auth/ui/LoginForm/LoginForm.stories.tsx
  src/features/auth/ui/LoginForm/LoginForm.tsx
  src/features/auth/ui/SignUpForm/SignUpForm.stories.tsx
  src/features/auth/ui/SignUpForm/SignUpForm.tsx
Labels: UI/UX, Feature

#32 로그인 api 연동 및 로그인 페이지 추가
  src/app/login/page.tsx
  src/features/auth/ui/LoginForm/LoginForm.tsx
Labels: Feature

#30 feat: 마이페이지 컴포넌트 구현
  src/entities/post/ui/card/PostCard.stories.ts
  src/entities/post/ui/card/PostCard.tsx
  src/entities/post/ui/card/assets/product_image.png
  src/entities/user/ui/card/Profile.stories.tsx
  src/entities/user/ui/card/Profile.tsx
  src/entities/user/ui/card/assets/profile.jpg
Labels: Feature

#33 fix: storybook 정적 경로 누락 수정
  .storybook/main.ts
  src/widgets/header/ui/Header.tsx
  src/widgets/header/ui/SearchForm.tsx
Labels: Bug Fix

#37 로그인 상태 관리 추가
  src/app/login/page.tsx
  src/features/auth/model/auth.store.ts
Labels: Feature

#44 style: dropdown 컴포넌트 tailwind 반응형 적용
  src/shared/ui/DropDown/DropDown.stories.tsx
  src/shared/ui/DropDown/DropDown.tsx
Labels: UI/UX

#41 style: 버튼 컴포넌트 tailwind 반응형 적용
  src/shared/ui/Button/Button.stories.ts
  src/shared/ui/Button/Button.tsx
Labels: UI/UX

#46 style: modal 컴포넌트 tailwind 반응형 적용
  src/shared/ui/Modal/Modal.stories.tsx
  src/shared/ui/Modal/Modal.tsx
Labels: UI/UX

#40 feat: PostCard 수정
  src/entities/post/ui/card/PostCard.tsx
Labels: Feature

#43 feat: profile 항목 및 로그아웃 버튼 추가
  src/entities/user/ui/card/Profile.tsx
Labels: Feature
